import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

 const HelloWorld = styled.div`
    color: red;
    font-size: 35px;
`


const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Nexstyt App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main><HelloWorld>Hello World!</HelloWorld></main>
        </div>
    )
}

export default Home
